.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.TH WMLSDASM 1 "3rd October 2000" "Kannel Project" "Kannel Project"
.SH NAME
wmlsdasm \- WMLScript disassembler
.SH SYNOPSIS
.B wmlsdasm
.BR "" [ -cfnh ]
.IR file ...
.SH DESCRIPTION
.B wmlsdasm
un-compilers WMLScript bytecode files into a source version.
It is useful for debugging the WMLScript compiler.
.SH "SEE ALSO"
.BR wmlsc (1),
.BR kannel (8).
