.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.TH WMLSC 1 "3rd October 2000" "Kannel Project" "Kannel Project"
.SH NAME
wmlsc \- WMLScript compiler
.SH SYNOPSIS
.B wmlsc
.BR "" [ -adlsv ]
.IR file ...
.SH DESCRIPTION
.B wmlsc
compiles WMLScript source files into a binary version.
It is useful for testing WMLScript file correctness.
.SH "SEE ALSO"
.BR wmlsdasm (1),
.BR kannel (8).
