.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.TH SEEWBMP 1 "3rd October 2000" "Kannel Project" "Kannel Project"
.SH NAME
seewbmp \- Convert a WBMP wireless bitmap to textual format
.SH SYNOPSIS
.B seewbmp
.IR "" [ inputfile ... ]
.SH DESCRIPTION
.B seewbmp
reads one or more wireless bitmap images (WBMP files) and prints them
to the standard output in a textual format.
Each pixel is shown as either a space or an asterisk.
.SH "SEE ALSO"
.BR kannel (8)
