<?xml version="1.0" encoding="UTF-8"?>
<!-- June 11, 2005 -->
<wsdl:definitions
   name="parlayx_sms_send_service"
   targetNamespace="http://www.csapi.org/wsdl/parlayx/sms/send/v2_1/service"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:tns="http://www.csapi.org/wsdl/parlayx/sms/send/v2_1/service"
   xmlns:interface="http://www.csapi.org/wsdl/parlayx/sms/send/v2_1/interface">

   <wsdl:import namespace="http://www.csapi.org/wsdl/parlayx/sms/send/v2_1/interface" location="parlayx_sms_send_interface_2_1.wsdl"/>

   <wsdl:binding name="SendSmsBinding" type="interface:SendSms">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="sendSms">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>

      <wsdl:operation name="sendSmsLogo">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>

      <wsdl:operation name="sendSmsRingtone">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>

      <wsdl:operation name="getSmsDeliveryStatus">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="SendSmsService">
      <wsdl:port name="SendSms" binding="tns:SendSmsBinding">
         <soap:address location="http://localhost:9080/ParlayXSms/services/SendSms"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
